version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data/processed:/data/processed
    ports:
      - 8123:8123
      - 9000:9000